### ISSUE TITLE
视频无法播放。

### ISSUE THREAD

**Issue by BigOrange128** [jokin1999/chaoxing-solution#1]
默认视频线路是本校，需要手动选择为公网线路。运行脚本时不会切换线路所以导致视频无法播放获取不到视频。
videojs-ext.min.js?v=20180913:1 Uncaught TypeError: Cannot set property 'mode' of undefined
    at VM5881 videojs-ext.min.js:1
(anonymous) @ videojs-ext.min.js?v=20180913:1
setTimeout (async)
success @ videojs-ext.min.js?v=20180913:1
callback @ all-classes.js?v=2018-0312-1524:1
Ext.data.Connection#onComplete @ all-classes.js?v=2018-0312-1524:1
Ext.data.Connection#onStateChange @ all-classes.js?v=2018-0312-1524:1
(anonymous) @ all-classes.js?v=2018-0312-1524:1
XMLHttpRequest.send (async)
Ext.data.Connection#request @ all-classes.js?v=2018-0312-1524:1
(anonymous) @ videojs-ext.min.js?v=20180913:1
(anonymous) @ video.js?v=20180910:3703
(anonymous) @ video.js?v=20180910:3702
bound @ video.js?v=20180910:2117
(anonymous) @ video.js?v=20180910:4370
setTimeout (async)
setTimeout @ video.js?v=20180910:4368
triggerReady @ video.js?v=20180910:3695
handleTechReady_ @ video.js?v=20180910:22575
bound @ video.js?v=20180910:2117
ready @ video.js?v=20180910:3677
loadTech_ @ video.js?v=20180910:22392
src_ @ video.js?v=20180910:24317
(anonymous) @ video.js?v=20180910:24265
setSourceHelper @ video.js?v=20180910:11350
(anonymous) @ video.js?v=20180910:11345
setSource @ video.js?v=20180910:55368
setSourceHelper @ video.js?v=20180910:11332
setSourceHelper @ video.js?v=20180910:11352
(anonymous) @ video.js?v=20180910:11178
bound @ video.js?v=20180910:2117
(anonymous) @ video.js?v=20180910:4370
setTimeout (async)
setTimeout @ video.js?v=20180910:4368
setSource @ video.js?v=20180910:11177
src @ video.js?v=20180910:24257
MediaLoader @ video.js?v=20180910:11565
addChild @ video.js?v=20180910:3464
handleAdd @ video.js?v=20180910:3586
initChildren @ video.js?v=20180910:3633
Player @ video.js?v=20180910:21822
videojs$1 @ video.js?v=20180910:26247
ans.VideoJs#constructor @ videojs-ext.min.js?v=20180913:1
ans.VideoJs @ all-classes.js?v=2018-0312-1524:1
showHTML5Player @ index.html?v=2018-0126-1905:525
success @ index.html?v=2018-0126-1905:716
callback @ all-classes.js?v=2018-0312-1524:1
Ext.data.Connection#onComplete @ all-classes.js?v=2018-0312-1524:1
Ext.data.Connection#onStateChange @ all-classes.js?v=2018-0312-1524:1
(anonymous) @ all-classes.js?v=2018-0312-1524:1
XMLHttpRequest.send (async)
Ext.data.Connection#request @ all-classes.js?v=2018-0312-1524:1
request @ index.html?v=2018-0126-1905:591
loadVideo @ index.html?v=2018-0126-1905:753
(anonymous) @ index.html?v=2018-0126-1905:782
(anonymous) @ all-classes.js?v=2018-0312-1524:1
Ext.util.Event#fire @ all-classes.js?v=2018-0312-1524:1
h.fire @ all-classes.js?v=2018-0312-1524:1
fireReadyEvent @ all-classes.js?v=2018-0312-1524:1
(anonymous) @ all-classes.js?v=2018-0312-1524:1
setTimeout (async)
defer @ all-classes.js?v=2018-0312-1524:1
fireDocReady @ all-classes.js?v=2018-0312-1524:1
onReadyEvent @ all-classes.js?v=2018-0312-1524:1
VM6115:65 【超星刷课】播放视频
index.html?v=2018-0126-1905:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
index.html?v=2018-0126-1905:1 Mixed Content: The page at 'https://mooc1-1.chaoxing.com/mycourse/studentstudy?chapterId=128209289&courseId=201856476&clazzid=4465611&enc=178f2b2cb594528b32b944a8c504697b' was loaded over HTTPS, but requested an insecure video 'http://10.37.1.79/s1.ananas.chaoxing.com/video/61/48/18/3599036f6a24800de38f9ca74d5ac8dc/sd.mp4'. This content should also be served over HTTPS.
10.37.1.79/s1.ananas.chaoxing.com/video/61/48/18/3599036f6a24800de38f9ca74d5ac8dc/sd.mp4:1 GET http://10.37.1.79/s1.ananas.chaoxing.com/video/61/48/18/3599036f6a24800de38f9ca74d5ac8dc/sd.mp4 0 ()
video.js?v=20180910:128 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

**Comment by josark2005** [comment]
抱歉，没有样本无法进行适配，脚本仅供学习交流，可以参考[协议分析](https://wr.twocola.com/2018/09/06/chaoxing-swf.html) 自行对协议进行匹配。
ps:当前脚本未使用协议方法刷课

**Comment by BigOrange128** [comment]
感谢回复，你在实验中可以加载出来视频吗？可不可以指定GET请求的地址？（我不懂js）或者脚本可不可以实现点击网页中视频播放器上的切换线路按钮？

**Comment by josark2005** [comment]
感谢反馈。
1、在我这里的实现是完全支持的。
2、最新的脚本没有使用协议，不存在GET问题
3、脚本可以做到点击切换线路按钮
以上
